name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    permissions:
      pull-requests: read
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install GPG
        run: |
          cat <(echo -e "${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Staging
        run: ./gradlew publish

      - name: Publish to Maven Central
        run: | 
          ./gradlew jreleaserFullRelease \
            -Dsigning.passphrase=${{ secrets.MAVEN_CENTRAL_GPG_SECRET_PASSWORD }} \ 
            -Djreleaser.mavencentral.username=${{ secrets.MAVEN_CENTRAL_USERNAME }} \
            -Djreleaser.mavencentral.password=${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Gradle Plugin Portal
        run: ./gradlew publishPlugins -Dgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Dgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}